-- sessions table
CREATE TABLE IF NOT EXISTS sessions (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT sessions_pk PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS sessions_IX1 ON sessions (SESSION_ID);

CREATE INDEX IF NOT EXISTS sessions_IX2 ON sessions (EXPIRY_TIME);

CREATE INDEX IF NOT EXISTS sessions_IX3 ON sessions (PRINCIPAL_NAME);

-- session attributes table
CREATE TABLE IF NOT EXISTS sessions_attributes (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    CONSTRAINT sessions_attributes_pk PRIMARY KEY (
        SESSION_PRIMARY_ID,
        ATTRIBUTE_NAME
    ),
    CONSTRAINT sessions_attributes_fk FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES sessions (PRIMARY_ID) ON DELETE CASCADE
);