name: SonarCloud Analysis Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarCloud analysis
        run: |
          mvn sonar:sonar -Pcoverage \
            -Dsonar.projectKey=T1WiLLi_Jolt \
            -Dsonar.organization=jolt-studio \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dgpg.skip=true